name: Check PR format

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master

env:
  BACKUP_ACCESS_KEY_ID: ${{ secrets.BACKUP_ACCESS_KEY_ID }}
  BACKUP_ENDPOINT: ${{ secrets.BACKUP_ENDPOINT }}
  BACKUP_FILE_BUCKET: ${{ secrets.BACKUP_FILE_BUCKET }}
  BACKUP_SECRET_ACCESS_KEY: ${{ secrets.BACKUP_SECRET_ACCESS_KEY }}
  BYRDOCS_CHECK_REPO_NAME: byrdocs-check
  BYRDOCS_CHECK_REPO_OWNER: byrdocs
  BYRDOCS_SITE_URL: ${{ secrets.BYRDOCS_SITE_URL }}
  BYRDOCS_SITE_TOKEN: ${{ secrets.BYRDOCS_SITE_TOKEN }}
  FILELIST_SITE_URL: ${{ secrets.FILELIST_SITE_URL }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_DATA_BUCKET: ${{ secrets.R2_DATA_BUCKET }}
  R2_FILE_BUCKET: ${{ secrets.R2_FILE_BUCKET }}

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Show log
        run: git log -5

      - name: Check for YAML files in root directory
        run: |
          files=$(find . -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \))
          if [ -n "$files" ]; then
            echo "根目录下发现 yml 或 yaml 文件，请移动到 metadata 目录中：" > comment.txt
            echo "$files" >> comment.txt
            exit 1
          fi

      - id: pdfium
        name: Get pdfium-binaries latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: bblanchon
          repo: pdfium-binaries

      - id: check
        name: Get byrdocs-check release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ${{ env.BYRDOCS_CHECK_REPO_OWNER }}
          repo: ${{ env.BYRDOCS_CHECK_REPO_NAME }}

      - name: Download release
        run: |
          wget https://github.com/bblanchon/pdfium-binaries/releases/download/${{ steps.pdfium.outputs.release }}/pdfium-linux-x64.tgz
          tar --overwrite -zxvf pdfium-linux-x64.tgz
          wget https://github.com/$BYRDOCS_CHECK_REPO_OWNER/$BYRDOCS_CHECK_REPO_NAME/releases/download/${{ steps.check.outputs.release }}/upload-metadata -O upload-metadata
          wget https://github.com/$BYRDOCS_CHECK_REPO_OWNER/$BYRDOCS_CHECK_REPO_NAME/releases/download/${{ steps.check.outputs.release }}/check-format -O check-format
          chmod 777 upload-metadata
          chmod 777 check-format

      - name: Check
        env:
          METADATA_DIR: ./metadata
        run: ./check-format > comment.txt 2>&1

      - name: Debug
        if: always()
        run: cat ./comment.txt

      - name: Read failure comment
        if: failure()
        id: comment
        run: |
          echo "body<<BYRDOCS_HEREDOC_EOF" >> $GITHUB_OUTPUT
          cat comment.txt                  >> $GITHUB_OUTPUT
          echo "BYRDOCS_HEREDOC_EOF"       >> $GITHUB_OUTPUT


      - name: Request changes review
        if: github.event_name == 'pull_request_target' && failure()
        uses: ntsd/auto-request-changes-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: ${{ steps.comment.outputs.body }}

      - name: Dismiss previous change requests
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            for (const review of reviews) {
              if (
                review.state === 'CHANGES_REQUESTED' &&
                review.user.login === 'github-actions[bot]'
              ) {
                await github.rest.pulls.dismissReview({
                  owner:        context.repo.owner,
                  repo:         context.repo.repo,
                  pull_number:  context.payload.pull_request.number,
                  review_id:    review.id,
                  message:      '格式检查已通过，此更改请求已解决。'
                });
              }
            }

